### ISSUE TITLE
Hyper-V Administrators group check fails

### ISSUE THREAD

**Issue by paul-green** [minishift/minishift#2047]
### General information

  * Minishift version: v1.12.0+daa0943
  * OS: Windows 10
  * Hypervisor: Hyper-V 

I found I couldn't start minishift due to the Hyper-V Admin check failing. I used  *warn-check-hyperv-driver* to get around this, but I believe I've found a solution after tinkering in Powershell.

source : cmd/minishift/cmd/start_preflight.go
function : checkHypervDriverUser

This fails (even though I'm in that local Hyper-V Administrators group;
````
checkIfMemberOfHyperVAdmins := `@([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole("S-1-5-32-578")`
````

I think it's to do with checking the string literally because It also fails in Powershell using that same string literal with ''The trust relationship between the primary domain and the trusted domain failed".

But if I use the SecurityIdentifier object overload of IsInRole() instead it works (returns true);
````
$sid = New-Object System.Security.Principal.SecurityIdentifier('S-1-5-32-578')
([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole($sid)
````

Checking for "Hyper-V Administrators" does work on my Powershell but causes issues on non-English Windows - #1541, #1566

Thanks
Paul

### Steps to reproduce
(one of those environment specific problems I think - may not fail on other machine).
  1. minishift start

### Expected
...
 Checking if user is a member of the Hyper-V Administrators group ... OK
...
### Actual
...
 Checking if user is a member of the Hyper-V Administrators group ... FAIL
...
### Logs

-- Starting profile 'minishift'
-- Checking if requested hypervisor 'hyperv' is supported on this platform ... OK
-- Checking if Hyper-V driver is installed ... OK
-- Checking if Hyper-V driver is configured to use a Virtual Switch ... OK
-- Checking if user is a member of the Hyper-V Administrators group ... FAIL
   See the 'Setting Up the Driver Plug-in' topic (https://docs.openshift.org/latest/minishift/getting-started/setting-up-driver-plugin.html) for more information
-- Checking the ISO URL ... OK
-- Starting local OpenShift cluster using 'hyperv' hypervisor ...
-- Starting Minishift VM .................

Related to;
#1541 
#1566

**Comment by praveenkumar** [comment]
@anjannath you need to look into it and see if we can update our preflight check around it.

**Comment by anjannath** [comment]
@paul-green Interesting, other users have faced this in scenarios where it is part of a Domain, Is you machine part of a windows domain? please check #1822

**Comment by anjannath** [comment]
Thanks for the mentiion @praveenkumar, but need more information like if the user is part of a windows domain, because others have faced this issue in that scenario, also the localization issue was fixed and haven't encountered it recently. After this information is known we can update the pre flight check.

**Comment by paul-green** [comment]
@anjannath - Yes this is my work machine on a domain - the DC is online and working OK.  This is a bit of an odd one. 

The docs for [IsInRole()](https://msdn.microsoft.com/en-us/library/system.security.principal.windowsprincipal.isinrole(v=vs.110).aspx) for the string overload state that is takes a 'specified name' for the group - so it's strange the using the SID string works for some people. 

It *should* only be the SecurityIdentifier overload that works in this scenario but if the current code works for others it's a bit strange.

**Comment by paul-green** [comment]
fyi I created https://github.com/minishift/minishift/pull/2050. I tested with a local build and it works as expected on my machine.

**Comment by paul-green** [comment]
I created a new PR https://github.com/minishift/minishift/pull/2052 to fix the commit message issue. Builds now pass

**Comment by LalatenduMohanty** [comment]
Resolved via #2052

**Comment by EagleIJoe** [comment]
The problem still exists and is within docker-machine. I have handed in the following PR to correct it: https://github.com/docker/machine/pull/4557

**Comment by EagleIJoe** [comment]
I used the latest stable as well as built from source. The problem lies not within your code in openshift but in the line I changed in docker/machine/drivers/hyper/... The previous code line errors out in PowerShell. Hence, your check in OpenShift works fine, but the later process of actually creating the machine errors out...

What exactly do you mean by proposing it to machine-drivers/machine?

**Comment by gbraad** [comment]
This needs to be handled for code-ready/crc: https://github.com/code-ready/crc/issues/8
