### ISSUE TITLE
Update retry timeout in cmd-openshift feature for deploying app

### ISSUE THREAD

**Issue by budhrg** [minishift/minishift#2357]
Sometimes 5 seconds retry timeout is not enough for checking the application status.

https://github.com/minishift/minishift/blob/a50f3df32d6b22d2e85c54b14e5a26ba192f0b58/test/integration/features/cmd-openshift.feature#L104-L107

See https://ci.centos.org/job/minishift-nightly-b2d/143/consoleFull

**Comment by LalatenduMohanty** [comment]
Resolved via #2351

**Comment by agajdosi** [comment]
nodejs-ex application deployment still fails on some PRs: https://ci.centos.org/job/minishift-pr/4198/consoleFull.

**Comment by LalatenduMohanty** [comment]
@agajdosi This issue was about increasing the timeout and it was fixed in the code. IMO we should not re-open this issue but create a new one.  I have created https://github.com/minishift/minishift/issues/2368.
